version: '4'
services:
  postgres:
    image: postgres:15
    container_name: db_order
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nebras2001
      POSTGRES_DB: db_order
      PGDATA: /var/lib/postgresql/data

    ports:
      - "5437:5432"
    volumes:
      - db_order_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - order_network
volumes:
  db_order_data:
    driver: local

networks:
  order_network:
    driver: bridge