version: '3.8'

services:
  db_order:
    image: postgres:15
    container_name: db_order
    environment:
      POSTGRES_DB: db_order         # Database name
      POSTGRES_USER: postgres        # Username for PostgreSQL
      POSTGRES_PASSWORD: nebras2001    # Password for PostgreSQL
      PGDATA: /var/lib/postgresql/data # Location to store database data
    ports:
      - "5433:5432"                  # Map PostgreSQL default port 5432 to host's 5437
    volumes:
      - db_order_data:/var/lib/postgresql/data # Persistent storage for PostgreSQL data
      - ./docker/POSTGRESSQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - order_network                # Custom network for better isolation and communication

volumes:
  db_order_data:
    driver: local                    # Use local driver for storing PostgreSQL data persistently

networks:
  order_network:
    driver: bridge                   # Use bridge network to isolate containers
