version: '4'
services:
  mysql:
    image: mysql:8.1.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3308:3306"  # Change the host port to 3308 or another free port
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint.initdb.d/init.sql
