version: '3'

services:
  db_bank:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5433:5432
  db_catalog:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5434:5432
  db_inventory:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5435:5432
  db_mailing:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_mailing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5436:5432
  db_order:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_order
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5437:5432
  db_payment:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_payment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5438:5432
  db_pricing:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_pricing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5439:5432
  db_rating:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_rating
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5440:5432
  db_reviews:
    image: pgvector/pgvector:pg15
    environment:
      POSTGRES_DB: db_reviews
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: azerty
    ports:
      - 5441:5432
#   mongo_example:
#     image: mongo:4.4
#     environment:
#       MONGO_INITDB_ROOT_USERNAME: root
#       MONGO_INITDB_ROOT_PASSWORD: azerty
#     ports:
#       - 27017:27017
  zookeeper:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
  kafka:
    image: strimzi/kafka:0.19.0-kafka-2.5.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#   iam:
#     image: quay.io/keycloak/keycloak:20.0.2
#     environment:
#       - KEYCLOAK_ADMIN=admin
#       - KEYCLOAK_ADMIN_PASSWORD=admin
#     ports:
#       - "8181:8080"
#     command:
#       - start-dev --import-realm
#     volumes:
#       - ./IAM:/opt/keycloak/data/import
#   search:
#     image: solr:8
#     ports:
#      - "8983:8983"
#     volumes:
#       - data:/var/solr
#     entrypoint:
#     - bash
#     - "-c"
#     - "precreate-core products-index; exec solr -f"
# volumes:
#   data: