FROM docker.elastic.co/elasticsearch/elasticsearch:8.13.4

# Set environment variables
ENV ES_JAVA_OPTS "-Xms512m -Xmx512m"

# Expose the Elasticsearch HTTP port
EXPOSE 9200

# Set the cluster name (important for multi-node setups)
ENV CLUSTER_NAME my-es-cluster

# Add the data and logs directories
VOLUME ["/usr/share/elasticsearch/data", "/usr/share/elasticsearch/logs"]