# Utiliser l'image officielle de Redis
FROM redis:7.0

# Configurer le dossier de travail pour Redis
WORKDIR /data

# Exposer le port par défaut de Redis
EXPOSE 6379

# Lancer Redis en mode par défaut
CMD ["redis-server"]