spring:
  application:
    name: SpringAPI
  datasource:
    url: jdbc:postgresql://localhost:5432/order_service
    username: postgres
    password: SQL_2023test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
logging:
  level:
    org:
      flywaydb : DEBUG

server:
  port: 8084
