spring:
  application:
    name: SpringAPI
  datasource:

    url: jdbc:postgresql://localhost:5432/db_order
    username: postgres
    password: azerty
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
    baseline-on-migrate: true
    locations: classpath:db/migration
  http:
    host: 0.0.0.0
    cors:
      enabled: true
      origins: "*"

logging:
  level:
    org:
      flywaydb: DEBUG

server:
  port: 8084