name: CI/CD Pipeline

on:
  push:
    branches:
      - service-catalog
  pull_request:
    branches:
      - service-catalog

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd catalog/catalog-service/
          mvn clean package -Dquarkus.package.type=uber-jar

      - name: Archive JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: service-catalog.jar
          path: catalog/catalog-service/target/catalog-service-1.0.0-SNAPSHOT-runner.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: Download JAR Artifact
        uses: actions/download-artifact@v3
        with:
          name: service-catalog.jar
          path: ./  

      - name: Add Server to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.DEPLOYMENT_MACHINE_IP }} >> ~/.ssh/known_hosts

      - name: Transfer JAR to VPS
        run: |
          sshpass -p "${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}" scp ./service-catalog.jar ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }}:~/service-catalog/service-catalog.jar

      - name: Deploy JAR to VPS
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOYMENT_MACHINE_IP }}
          username: ${{ secrets.DEPLOYMENT_MACHINE_USER }}
          password: ${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}
          script: |
            mkdir -p ~/service-catalog
            pkill -f 'java.*service-catalog.jar' || true
            nohup java -jar ~/service-catalog/service-catalog.jar --server.port=8082 > ~/service-catalog/app.log 2>&1 &
