name: Mailing CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Maven
      run: mvn clean package -DskipTests
      working-directory: mailing

    - name: Deploy JAR to VPS
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.DEPLOYMENT_MACHINE_IP }}
        username: ${{ secrets.DEPLOYMENT_MACHINE_USER }}
        password: ${{ secrets.DEPLOYMENT_MACHINE_USER_PSW }}
        script: |
          scp -o StrictHostKeyChecking=no mailing/target/service-mailing.jar ${{ secrets.DEPLOYMENT_MACHINE_USER }}@${{ secrets.DEPLOYMENT_MACHINE_IP }}:~/mailing-service/
          sleep 10

          echo "Starting Spring Boot service..."
          cd ~/mailing-service
          nohup java -jar service-mailing.jar --server.port=8081 > service-mailing.log 2>&1 &
          echo "Spring Boot service deployed successfully!"

          sleep 30

          echo "Performing health check..."
          curl -X 'GET' 'http://localhost:8081' -H 'accept: application/json' || (echo "Service health check failed!" && exit 1)

          echo "Service deployed and healthy!"
          
          tail -n 50 ~/mailing-service/service-mailing.log