name: CI/CD Pipeline

on:
  push:
    branches:
      - Pricing
  pull_request:
    branches:
      - Pricing

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          cd search/
          mvn clean package -DskipTests

      - name: Archive JAR Artifact
        uses: actions/upload-artifact@v3
        with:
          name: service-pricing.jar
          path: pricing/target/*.jar

 
